version: '2'

services:
  uppy:
    image: transloadit/companion
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/app
      - /app/node_modules
      - /mnt/uppy-server-data:/mnt/uppy-server-data
    ports:
      - "3020:3020"
    command: "/app/src/standalone/start-server.js --config nodemon.json"
    env_file:
     - .env
