# Hexo Configuration
## Docs: http://zespia.tw/hexo/docs/configuration.html
## Source: https://github.com/tommy351/hexo/

# Theme
google_analytics: UA-63083-12
root_domain: uppy.io

# Site
title: Uppy
subtitle: "Almost as cute as a puppy"
logo_large: /images/uppy-logo-full.svg
logo_medium: /images/uppy.svg
logo_icon: /images/uppy.png
description: >
  Uppy is (going to be) a JavaScript file uploader that fetches files from Dropbox, Instagram, local disk, remote URLs, and other exciting locations.
  It has a plugin-based architecture, first-class support for resumable uploads according to the open standard: <a href="http://tus.io">tus</a>,
  and custom encoding backends, making it extensible and robust. Uppy is in the early stages of development
  and should not be used for anything serious yet.
descriptionWho: >
  Uppy is brought to you by the people
  behind <a href="https://transloadit.com">Transloadit</a> and as such has first class support
  for adding their uploading and encoding backend, but this is opt-in,
  and you can just as easily roll your own.
author: Transloadit
email: uppybot@uppy.io
language: English

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://uppy.io
root: /
permalink: :year/:month/:day/:title/
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: examples

# Directory
source_dir: src
public_dir: public

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
auto_spacing: false # Add spaces between asian characters and western characters
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
max_open_file: 100
multi_thread: true
filename_case: 0
render_drafts: false
post_asset_folder: false
highlight:
  enable: true
  line_number: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Archives
## 2: Enable pagination
## 1: Disable pagination
## 0: Fully Disable
archive: 0
category: 0
tag: 0

# Server
## Hexo uses Connect as a server
## You can customize the logger format as defined in
## http://www.senchalabs.org/connect/logger.html
port: 4000
logger: false
logger_format:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: MMM D YYYY
time_format: H:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Disqus
disqus_shortname:

# Extensions
## Plugins: https://github.com/tommy351/hexo/wiki/Plugins
## Themes: https://github.com/tommy351/hexo/wiki/Themes
theme: uppy
exclude_generator:

# hexo-tag-emojis plugin configuration
emojis:
  image_dir: images/emojis

# Markdown
## https://github.com/chjj/marked
markdown:
  gfm: true
  pedantic: false
  sanitize: false
  tables: true
  breaks: true
  smartLists: true
  smartypants: true

node_sass:
  debug: false
  outputStyle: compressed
  precision: 5
  sourceComments: false

postcss:
  plugins:
    postcss-inline-svg:
      path: 'src/images'
    autoprefixer:
      browsers:
        - 'last 2 versions'
    cssnano:

browsersync:
  files: 'public/examples/**/*.js'
  watchOptions:
    awaitWriteFinish:
      - stabilityThreshold: 3000
      - pollInterval: 100

skip_render:
  - '*.js'
  - '**/*.js'
  - '*.es6'
  - '**/*.es6'
